name: Deploy

on:
  push:
    tags:
      - v**

jobs:
  Deploy:
    runs-on: arc-rs-ncuhome
    steps:
      - uses: actions/checkout@v6

      - name: Setup Ko
        uses: ko-build/setup-ko@v0.9
        with:
          use-sudo: true

      - name: Login to Registry
        env:
          registry: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        run: echo "$password" | ko login "$registry" -u "$username" --password-stdin

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: Build Image and Push
        env:
          KO_DOCKER_REPO: "${{ secrets.REGISTRY_URI }}/feishu-git-push-bot/core"
          KO_GFLAGS: >-
            -trimpath
            -ldflags='-s -w -extldflags "-static"'
        run: ko build --sbom none --bare --tags latest,${{ github.ref_name }} .

      - name: Update Workload
        uses: MultiMx/K8sSetImageAction@v0.8
        with:
          server: ${{ secrets.CATTLE_SERVER }}
          token: ${{ secrets.CATTLE_TOKEN }}
          namespace: feishu-git-push-bot
          workload: core
          wait: true
          image: "${{ secrets.REGISTRY_URI }}/feishu-git-push-bot/core:${{ github.ref_name }}"
